import { FormEvent, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Check, Eye, EyeOff, FileCheck2, LockKeyhole, MonitorSmartphone, ShieldCheck } from "lucide-react";
import { Wordmark } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { useAppState } from "@/state/app-state";
import { cn } from "@/lib/utils";

const editorialAsset=(name:string)=>`${import.meta.env.BASE_URL}assets/editorial/${name}`;

type Errors=Partial<Record<'name'|'email'|'password'|'ack',string>>;
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export function SignUpPage(){
  const navigate=useNavigate();const state=useAppState();
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [ack,setAck]=useState(false);const [show,setShow]=useState(false);const [errors,setErrors]=useState<Errors>({});
  const nameRef=useRef<HTMLInputElement>(null);const emailRef=useRef<HTMLInputElement>(null);const passwordRef=useRef<HTMLInputElement>(null);const ackRef=useRef<HTMLInputElement>(null);
  const validate=(field?:keyof Errors)=>{const next:Errors={...errors};if(!field||field==='name')next.name=name.trim()?'':'Enter a display name for the form preview.';if(!field||field==='email')next.email=emailPattern.test(email)?'':'Enter a valid email format.';if(!field||field==='password')next.password=password.length>=8?'':'Use at least 8 characters for this sample.';if(!field||field==='ack')next.ack=ack?'':'Confirm that you understand this is a local sample.';setErrors(next);return next};
  const submit=(event:FormEvent)=>{event.preventDefault();const next=validate();const first=(['name','email','password','ack'] as const).find(key=>next[key]);if(first){({name:nameRef,email:emailRef,password:passwordRef,ack:ackRef}[first].current)?.focus();return}state.setOnboardingCompleted(false);navigate('/onboarding?from=signup')};
  return <AuthShell title="Preview sample setup" intro="Try the production-style form validation, then continue to the interactive onboarding sample. No profile or session is created.">
    <form onSubmit={submit} noValidate className="mt-7 space-y-4">
      <Field id="signup-name" label="Display name preview" error={errors.name}><input ref={nameRef} id="signup-name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} onBlur={()=>validate('name')} aria-invalid={!!errors.name} aria-describedby={errors.name?'signup-name-error':undefined} className="field"/></Field>
      <Field id="signup-email" label="Email" error={errors.email}><input ref={emailRef} id="signup-email" type="email" inputMode="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} onBlur={()=>validate('email')} aria-invalid={!!errors.email} aria-describedby={errors.email?'signup-email-error':undefined} className="field"/></Field>
      <PasswordField id="signup-password" label="Sample password" value={password} setValue={setPassword} show={show} setShow={setShow} inputRef={passwordRef} error={errors.password} onBlur={()=>validate('password')} autoComplete="new-password"/>
      <p className="rounded-2xl bg-recessed p-3 text-xs leading-5 text-muted"><strong className="text-ink">Do not reuse a real password.</strong> This value stays only in the current page session and is not stored or sent.</p>
      <label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-rule bg-white p-3"><input ref={ackRef} type="checkbox" checked={ack} onChange={e=>{setAck(e.target.checked);setErrors(value=>({...value,ack:undefined}))}} aria-invalid={!!errors.ack} aria-describedby={errors.ack?'signup-ack-error':undefined} className="mt-1 size-5 shrink-0 accent-pencil"/><span className="text-xs leading-5">I understand this is a local interactive sample; no user or bank account is created.</span></label>{errors.ack&&<p id="signup-ack-error" className="-mt-2 text-xs font-semibold text-coral" aria-live="polite">{errors.ack}</p>}
      <Button type="submit" size="lg" className="w-full">Continue to sample setup</Button>
    </form>
    <p className="mt-5 flex min-h-11 items-center justify-center text-center text-sm text-muted">Previewing a return visit? <Link className="-my-3 ml-1 flex min-h-11 items-center font-bold text-pencil" to="/sign-in">Sign-in flow</Link></p>
  </AuthShell>
}

export function SignInPage(){
  const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [errors,setErrors]=useState<Errors>({});const emailRef=useRef<HTMLInputElement>(null);const passwordRef=useRef<HTMLInputElement>(null);
  const submit=(event:FormEvent)=>{event.preventDefault();const next:Errors={email:emailPattern.test(email)?'':'Enter a valid email format.',password:password.length>=8?'':'Enter at least 8 characters.'};setErrors(next);if(next.email){emailRef.current?.focus();return}if(next.password){passwordRef.current?.focus();return}navigate('/today')};
  return <AuthShell title="Preview returning-user sign in" intro="Try the validation and open the local workspace. Any correctly formatted sample values work; no account lookup or session occurs."><form onSubmit={submit} noValidate className="mt-7 space-y-4"><Field id="signin-email" label="Email" error={errors.email}><input ref={emailRef} id="signin-email" type="email" inputMode="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} onBlur={()=>setErrors(v=>({...v,email:emailPattern.test(email)?undefined:'Enter a valid email format.'}))} aria-invalid={!!errors.email} aria-describedby={errors.email?'signin-email-error':undefined} className="field"/></Field><PasswordField id="signin-password" label="Sample password" value={password} setValue={setPassword} show={show} setShow={setShow} inputRef={passwordRef} error={errors.password} onBlur={()=>setErrors(v=>({...v,password:password.length>=8?undefined:'Enter at least 8 characters.'}))} autoComplete="current-password"/><div className="flex justify-end"><Link to="/forgot-password" className="flex min-h-11 items-center text-sm font-bold text-pencil">Forgot password?</Link></div><Button type="submit" size="lg" className="w-full">Continue to sample workspace</Button><Button asChild type="button" size="lg" variant="outline" className="w-full"><Link to="/today">Explore without signing in</Link></Button></form><p className="mt-5 flex min-h-11 items-center justify-center text-center text-sm text-muted">Want the first-visit flow? <Link className="-my-3 ml-1 flex min-h-11 items-center font-bold text-pencil" to="/sign-up">Setup preview</Link></p></AuthShell>
}

export function ForgotPasswordPage(){
  const [email,setEmail]=useState('');const [error,setError]=useState('');const [sent,setSent]=useState(false);const ref=useRef<HTMLInputElement>(null);
  const submit=(event:FormEvent)=>{event.preventDefault();if(!emailPattern.test(email)){setError('Enter a valid email format.');ref.current?.focus();return}setError('');setSent(true)};
  return <AuthShell title="Reset the sample password" intro="This state demonstrates recovery copy only; there is no email service in the local demo.">{sent?<div className="mt-7 rounded-[22px] border border-pencil/15 bg-pencil/[.04] p-5" role="status"><span className="grid size-11 place-items-center rounded-2xl bg-pencil text-white"><Check className="size-5"/></span><h2 className="mt-4 text-lg font-bold">No email was sent</h2><p className="mt-2 text-sm leading-6 text-muted">This is a local interaction sample. Your entered email was not stored or transmitted.</p><Button asChild variant="outline" className="mt-5 w-full"><Link to="/sign-in">Return to sign in</Link></Button></div>:<form onSubmit={submit} noValidate className="mt-7 space-y-4"><Field id="reset-email" label="Email" error={error}><input ref={ref} id="reset-email" type="email" inputMode="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} aria-invalid={!!error} aria-describedby={error?'reset-email-error':undefined} className="field"/></Field><Button type="submit" size="lg" className="w-full">Show recovery state</Button></form>}</AuthShell>
}

function AuthShell({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <div className="paper-grain min-h-dvh bg-paper sm:p-5"><div className="mx-auto min-h-dvh max-w-[1040px] overflow-hidden sm:min-h-[calc(100dvh-40px)] sm:rounded-[28px] sm:border sm:border-rule sm:bg-sheet sm:shadow-card lg:grid lg:grid-cols-[.9fr_1.1fr]"><section className="flex min-h-dvh flex-col px-5 pb-8 pt-4 sm:min-h-0 sm:px-8 lg:p-10"><header className="flex h-12 items-center"><Link to="/" className="grid size-11 place-items-center rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil" aria-label="Back to landing"><ArrowLeft className="size-5"/></Link><div className="mx-auto"><Wordmark/></div><div className="size-11"/></header><main className="mx-auto flex w-full max-w-[430px] flex-1 flex-col justify-center py-7"><span className="inline-flex w-fit rounded-full bg-citron px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.1em]">Interactive sample</span><h1 className="mt-5 text-[36px] font-bold leading-[1.02] tracking-[-.055em]">{title}</h1><p className="mt-3 text-sm leading-6 text-muted">{intro}</p><div className="mt-4 flex gap-2 rounded-2xl border border-coral/15 bg-coral/[.045] p-3 text-xs leading-5 text-muted"><MonitorSmartphone className="mt-0.5 size-4 shrink-0 text-coral"/><span><strong className="text-ink">Local demo only.</strong> No profile or session is created, and entries are discarded on navigation.</span></div>{children}</main></section><aside className="relative hidden overflow-hidden bg-ink p-10 text-white lg:flex lg:flex-col lg:justify-between"><img src={editorialAsset("ledger-folios.png")} alt="" aria-hidden="true" className="pointer-events-none absolute -right-10 -top-8 w-48 rotate-6 opacity-[.12] grayscale"/><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-citron">Why the sample asks</p><h2 className="mt-3 max-w-[430px] text-[42px] font-bold leading-[1.02] tracking-[-.05em]">Identity first. Bank connection later.</h2><p className="mt-4 max-w-[440px] text-sm leading-6 text-white/60">A production user account and a financial-source connection would remain separate decisions.</p></div><div className="relative space-y-3"><AuthProof icon={MonitorSmartphone} text="The local sample does not create a user account"/><AuthProof icon={LockKeyhole} text="No password is stored, logged, or sent"/><AuthProof icon={ShieldCheck} text="Onboarding explains connection permissions separately"/><AuthProof icon={FileCheck2} text="You review the plan before using it"/></div></aside></div></div>}
function Field({id,label,error,children}:{id:string;label:string;error?:string;children:React.ReactNode}){return <div><label htmlFor={id} className="mb-2 block text-sm font-semibold">{label}</label>{children}{error&&<p id={`${id}-error`} className="mt-1.5 text-xs font-semibold text-coral" aria-live="polite">{error}</p>}</div>}
function PasswordField({id,label,value,setValue,show,setShow,inputRef,error,onBlur,autoComplete}:{id:string;label:string;value:string;setValue:(v:string)=>void;show:boolean;setShow:(v:boolean)=>void;inputRef:React.RefObject<HTMLInputElement>;error?:string;onBlur:()=>void;autoComplete:string}){return <div><label htmlFor={id} className="mb-2 block text-sm font-semibold">{label}</label><div className={cn("flex h-14 items-center rounded-2xl border bg-white focus-within:ring-2 focus-within:ring-pencil",error?'border-coral':'border-rule')}><input ref={inputRef} id={id} type={show?'text':'password'} autoComplete={autoComplete} value={value} onChange={e=>setValue(e.target.value)} onBlur={onBlur} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined} className="h-full min-w-0 flex-1 rounded-l-2xl bg-transparent px-4 text-base outline-none"/><button type="button" onClick={()=>setShow(!show)} className="grid size-12 place-items-center rounded-xl text-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil" aria-label={show?'Hide password':'Show password'} aria-pressed={show}>{show?<EyeOff className="size-5"/>:<Eye className="size-5"/>}</button></div>{error&&<p id={`${id}-error`} className="mt-1.5 text-xs font-semibold text-coral" aria-live="polite">{error}</p>}</div>}
function AuthProof({icon:Icon,text}:{icon:typeof ShieldCheck;text:string}){return <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4"><span className="grid size-10 place-items-center rounded-2xl bg-white/10 text-citron"><Icon className="size-5"/></span><span className="text-sm font-semibold">{text}</span></div>}
