import { useState } from "react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { Bell, ChevronRight, Database, Eye, LockKeyhole, Shield, SlidersHorizontal, Users, WalletCards } from "lucide-react";
import { MobileShell } from "@/components/layout";
import { PlanCalibration } from "@/components/plan-calibration";
import { Button } from "@/components/ui/button";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Switch } from "@/components/ui/switch";
import { calculatePlanProjection, useAppState, type HouseholdMode, type NotificationMode } from "@/state/app-state";
import { money } from "@/lib/utils";

const sections = [
  { slug: "calibration", icon: WalletCards, title: "Plan calibration", detail: "Cash, income, commitments, and guardrails" },
  { slug: "household", icon: Users, title: "Household", detail: "Members, roles, and planning context" },
  { slug: "notifications", icon: Bell, title: "Notifications", detail: "Decisions, outcomes, and digests" },
  { slug: "planning", icon: SlidersHorizontal, title: "Planning rules", detail: "Safety buffer and forecast behavior" },
  { slug: "privacy", icon: Shield, title: "Privacy & data", detail: "Permissions, retention, and access" },
] as const;

export function SettingsIndexPage() {
  const state = useAppState();
  return <MobileShell><main className="px-4 pb-8 pt-5"><p className="eyebrow">Your operating rules</p><h1 className="text-[31px] font-bold tracking-[-0.045em]">Settings</h1><p className="mt-1 text-sm text-muted">Control how Budgefi plans, communicates, and uses connected data.</p><section className="mt-5 overflow-hidden rounded-[22px] border border-rule bg-white">{sections.map(({slug,icon:Icon,title,detail})=><Link key={slug} to={`/settings/${slug}`} className="flex min-h-[76px] items-center gap-3 border-b border-rule px-4 py-3 last:border-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-pencil"><span className="grid size-10 place-items-center rounded-2xl bg-recessed text-pencil"><Icon className="size-5"/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{title}</strong><span className="block truncate text-xs text-muted">{detail}</span></span><ChevronRight className="size-4 text-muted"/></Link>)}</section><section className="mt-6 rounded-[22px] border border-pencil/15 bg-pencil/[.035] p-4"><p className="text-xs font-bold uppercase tracking-[.1em] text-pencil">Current configuration</p><div className="mt-3 grid grid-cols-2 gap-2"><Summary label="Household" value={state.householdMode==='shared'?'Shared':'Personal'}/><Summary label="Safety buffer" value={money(state.planningBuffer)}/><Summary label="Alerts" value={state.notificationMode==='exceptions'?'Exceptions':state.notificationMode}/><Summary label="Weekly digest" value={state.weeklyDigest?'On':'Off'}/></div></section><Button asChild variant="outline" className="mt-5 w-full"><Link to="/onboarding">Replay onboarding</Link></Button></main></MobileShell>
}

export function SettingsDetailPage(){const {section}=useParams();if(!sections.some(item=>item.slug===section))return <Navigate to="/settings" replace/>;return <MobileShell><main className="px-4 pb-8 pt-5">{section==="calibration"&&<CalibrationSettings/>}{section==="household"&&<HouseholdSettings/>}{section==="notifications"&&<NotificationSettings/>}{section==="planning"&&<PlanningSettings/>}{section==="privacy"&&<PrivacySettings/>}</main></MobileShell>}

function CalibrationSettings(){const navigate=useNavigate();return <PlanCalibration onBack={()=>navigate("/settings")} onComplete={()=>navigate("/plan")}/>}

function HouseholdSettings(){const state=useAppState();return <><p className="eyebrow">Settings</p><h1 className="text-[29px] font-bold tracking-[-0.045em]">Household</h1><p className="mt-1 text-sm leading-5 text-muted">Choose the sample planning model and preview who could decide.</p><RadioGroup value={state.householdMode} onValueChange={value=>state.setHouseholdMode(value as HouseholdMode)} className="mt-5 space-y-2"><SettingChoice value="solo" icon={LockKeyhole} title="Personal plan" detail="One decision-maker and private activity."/><SettingChoice value="shared" icon={Users} title="Shared household" detail="Members can confirm shared bills and reimbursements."/></RadioGroup>{state.householdMode==='shared'&&<section className="mt-6"><h2 className="text-sm font-bold">Sample members</h2><div className="mt-2 divide-y divide-rule overflow-hidden rounded-[20px] border border-rule bg-white"><Member initials="MA" name="Maya" role="Simulated owner · full access"/><Member initials="AL" name="Alex" role="Simulated member · review and confirm"/></div><div className="mt-3 rounded-2xl bg-recessed p-4 text-xs leading-5 text-muted">Household roles are not provisioned in this prototype. In production, members would use separate access and never share bank credentials.</div></section>}</>}

function NotificationSettings(){const state=useAppState();return <><p className="eyebrow">Settings</p><h1 className="text-[29px] font-bold tracking-[-0.045em]">Notifications</h1><p className="mt-1 text-sm leading-5 text-muted">Preview how often Budgefi would ask for attention. This local prototype does not send notifications.</p><RadioGroup value={state.notificationMode} onValueChange={value=>state.setNotificationMode(value as NotificationMode)} className="mt-5 space-y-2"><TextChoice value="exceptions" title="Only when I need to decide" detail="Recommended · quietest"/><TextChoice value="daily" title="One daily summary" detail="Open work and meaningful changes"/><TextChoice value="all" title="All detected changes" detail="Highest frequency"/></RadioGroup><section className="mt-5 overflow-hidden rounded-[20px] border border-rule bg-white"><ToggleRow title="Weekly proof digest" detail="Preference only · no delivery active" checked={state.weeklyDigest} onChange={state.setWeeklyDigest}/><ToggleRow title="Connection health" detail="Production default preview · no delivery active" checked onChange={()=>{}} disabled/></section><div className="mt-4 rounded-2xl bg-pencil/[.05] p-4 text-xs leading-5 text-muted"><strong className="text-pencil">Quiet by design:</strong> the production intent is to avoid alerts for ordinary purchases.</div></>}

function PlanningSettings(){
  const state=useAppState();const [draft,setDraft]=useState(state.planningBuffer);const [saved,setSaved]=useState(false);const available=calculatePlanProjection(state.calibration,draft).available;const changed=draft!==state.planningBuffer;const shortfall=available<0;
  return <><p className="eyebrow">Settings</p><h1 className="text-[29px] font-bold tracking-[-0.045em]">Planning rules</h1><p className="mt-1 text-sm leading-5 text-muted">These rules change the plan immediately and remain visible in its calculation.</p><label className="mt-6 block text-sm font-semibold" htmlFor="planning-buffer">Safety buffer</label><p className="mt-1 text-xs text-muted">Held back from available-to-use for surprises.</p><div className="mt-3 flex h-14 items-center rounded-2xl border border-rule bg-white px-4 focus-within:ring-2 focus-within:ring-pencil"><span className="text-lg font-semibold text-muted">$</span><input id="planning-buffer" type="number" min="0" max="2000" inputMode="decimal" value={draft} onChange={event=>{setDraft(Math.max(0,Number(event.target.value)||0));setSaved(false)}} className="h-full min-w-0 flex-1 bg-transparent px-2 text-xl font-bold outline-none"/></div><div className="mt-4 rounded-[20px] bg-ink p-4 text-white"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-citron">{shortfall?'Projected shortfall':state.sourceStale?'Partial-data preview':'Plan consequence'}</p><p className="mt-1 text-2xl font-bold tabular-nums">{money(Math.abs(available))} {shortfall?'shortfall':'preview'}</p><p className="mt-1 text-xs text-white/60">{state.sourceStale?'Before unobserved MetroCard activity · ':''}through September 8</p></div><Button disabled={!changed} onClick={()=>{state.savePlanningBuffer(draft);setSaved(true)}} className="mt-5 w-full">Save planning rule</Button>{saved&&<Button asChild variant="outline" className="mt-2 w-full"><Link to="/plan">View updated plan</Link></Button>}<section className="mt-7"><h2 className="text-sm font-bold">Forecast behavior</h2><div className="mt-2 overflow-hidden rounded-[20px] border border-rule bg-white"><StaticRow title="Planning horizon" detail="Next 10 days"/><StaticRow title="Future income" detail="Exclude until observed"/><StaticRow title="Planned savings" detail="Reserve now for this horizon"/></div></section></>}

function PrivacySettings(){return <><p className="eyebrow">Settings</p><h1 className="text-[29px] font-bold tracking-[-0.045em]">Privacy & data</h1><p className="mt-1 text-sm leading-5 text-muted">Understand what Budgefi can see, retain, and do.</p><section className="mt-5 overflow-hidden rounded-[20px] border border-rule bg-white"><Permission icon={Eye} title="Read balances and transactions" detail="Used for reconciliation and cash coverage"/><Permission icon={LockKeyhole} title="No bank passwords stored" detail="Authentication remains with the connection provider"/><Permission icon={Shield} title="No money movement" detail="This product operates read-only"/></section><section className="mt-6"><h2 className="text-sm font-bold">Data controls</h2><div className="mt-2 overflow-hidden rounded-[20px] border border-rule bg-white"><Link to="/connections" className="flex min-h-[68px] items-center gap-3 px-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-pencil"><Database className="size-5 text-pencil"/><span className="flex-1"><strong className="block text-sm">Connected sources</strong><span className="text-xs text-muted">Review or revoke access</span></span><ChevronRight className="size-4 text-muted"/></Link></div></section><div className="mt-5 rounded-2xl bg-recessed p-4 text-xs leading-5 text-muted">Deleting the production account would require re-authentication and a typed confirmation. Destructive controls are intentionally not simulated in this clickable demo.</div></>}

function Summary({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-pencil/10 bg-white/70 p-3"><span className="block text-[10px] font-bold uppercase tracking-[.08em] text-muted">{label}</span><strong className="mt-1 block text-sm capitalize">{value}</strong></div>}
function SettingChoice({value,icon:Icon,title,detail}:{value:string;icon:typeof Users;title:string;detail:string}){return <label className="flex min-h-[76px] cursor-pointer items-center gap-3 rounded-[20px] border border-rule bg-white p-3 has-[[data-state=checked]]:border-pencil"><span className="grid size-10 place-items-center rounded-2xl bg-recessed text-pencil"><Icon className="size-5"/></span><span className="flex-1"><strong className="block text-sm">{title}</strong><span className="text-xs text-muted">{detail}</span></span><RadioGroupItem value={value}/></label>}
function TextChoice({value,title,detail}:{value:string;title:string;detail:string}){return <label className="flex min-h-[68px] cursor-pointer items-center gap-3 rounded-2xl border border-rule bg-white p-3 has-[[data-state=checked]]:border-pencil"><RadioGroupItem value={value}/><span><strong className="block text-sm">{title}</strong><span className="text-xs text-muted">{detail}</span></span></label>}
function Member({initials,name,role}:{initials:string;name:string;role:string}){return <div className="flex min-h-[68px] items-center gap-3 px-4"><span className="grid size-10 place-items-center rounded-2xl bg-citron text-xs font-bold">{initials}</span><span><strong className="block text-sm">{name}</strong><span className="text-xs text-muted">{role}</span></span></div>}
function ToggleRow({title,detail,checked,onChange,disabled=false}:{title:string;detail:string;checked:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <div className="flex min-h-[72px] items-center gap-3 border-b border-rule px-4 last:border-0"><span className="flex-1"><strong className="block text-sm">{title}</strong><span className="text-xs text-muted">{detail}</span></span><Switch checked={checked} onCheckedChange={onChange} label={title} disabled={disabled}/></div>}
function StaticRow({title,detail}:{title:string;detail:string}){return <div className="flex min-h-[62px] items-center justify-between gap-4 border-b border-rule px-4 last:border-0"><span className="text-sm font-semibold">{title}</span><span className="text-right text-xs text-muted">{detail}</span></div>}
function Permission({icon:Icon,title,detail}:{icon:typeof Eye;title:string;detail:string}){return <div className="flex min-h-[76px] items-center gap-3 border-b border-rule px-4 py-3 last:border-0"><span className="grid size-10 place-items-center rounded-2xl bg-recessed text-pencil"><Icon className="size-5"/></span><span><strong className="block text-sm">{title}</strong><span className="mt-0.5 block text-xs leading-4 text-muted">{detail}</span></span></div>}
