import { Link } from "react-router-dom";
import { CalendarDays, ChevronRight, CloudOff, House, PenLine, ShieldCheck, Tv, Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { HealthSheet, MobileShell } from "@/components/layout";
import { MoneySummary } from "@/components/money-summary";
import { useAppState } from "@/state/app-state";
import { money } from "@/lib/utils";

export function TodayPage(){
  const {sourceStale,commitments,authoritativeProjection,dataMode,manualActuals,accounts,cases}=useAppState();
  const manual=dataMode==="manual";
  const manualAsOf=accounts.find(account=>account.provenance==="manual")?.balanceAsOf;
  const manualFreshness=manualAsOf?`Last confirmed ${new Date(manualAsOf).toLocaleDateString([],{month:"short",day:"numeric"})}`:"Add your current cash total";
  const iconFor=(name:string)=>name.toLowerCase().includes("rent")?House:name.toLowerCase().includes("electric")?Zap:name.toLowerCase().includes("stream")?Tv:CalendarDays;
  const upcoming=commitments.filter(item=>item.dueDate).slice(0,3).map(item=>({icon:iconFor(item.name),label:item.name,meta:`${formatDate(item.dueDate!)} · ${item.provenance==="manual"?"you entered":item.provenance}`,amount:money(Number(BigInt(item.amount.minor))/100)}));
  const openCase=cases.find(item=>item.status==="open"||item.status==="awaiting_verification");
  return <MobileShell><main className="px-4 pb-8 pt-5">
    <div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] text-muted"><CalendarDays className="size-4" strokeWidth={1.8}/>{new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date())}</div>
    <MoneySummary/>
    {manual&&<Link to="/manual" className="mt-3 flex min-h-[68px] items-center gap-3 rounded-2xl border border-pencil/15 bg-white px-4 py-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-citron"><PenLine className="size-5"/></span><span className="min-w-0 flex-1"><strong className="block text-sm">Manual plan</strong><span className="block truncate text-xs text-muted">{manualFreshness} · tap to update</span></span><ChevronRight className="size-4 text-muted"/></Link>}
    {sourceStale&&!manual&&<div className="mt-3 flex items-center justify-between gap-3 rounded-2xl border border-amber-500/25 bg-amber-50 px-4 py-3"><div className="flex min-w-0 items-center gap-3"><CloudOff className="size-5 shrink-0 text-amber-700"/><div className="min-w-0"><p className="text-sm font-semibold">An included account needs attention</p><p className="truncate text-xs text-muted">Coverage is stale or missing</p></div></div><HealthSheet><Button size="sm" variant="outline">Fix</Button></HealthSheet></div>}
    <section className="mt-7" aria-labelledby="review-heading"><div className="mb-3 flex items-end justify-between"><div><p className="eyebrow">{manual?"Needs your input":"Verifier status"}</p><h1 id="review-heading" className="text-[27px] font-bold leading-none tracking-[-.035em]">{manual?"Your manual check-in":openCase?"A possible duplicate needs review":"No exceptions need review"}</h1></div><Badge>{manual?`${manualActuals.length} recorded`:"Current"}</Badge></div>
      {manual?<article className="overflow-hidden rounded-[24px] border border-pencil/15 bg-white p-5 shadow-card"><span className="grid size-12 place-items-center rounded-2xl bg-recessed text-pencil"><PenLine className="size-6"/></span><h2 className="mt-4 text-xl font-bold tracking-[-.025em]">Keep the plan current in a few taps</h2><p className="mt-1 text-sm leading-5 text-muted">Update today’s spendable balance, record a charge, or add an upcoming commitment. Manual entries always stay clearly labeled.</p><Button asChild className="mt-4 w-full" size="lg"><Link to="/manual">Open manual workspace <ChevronRight className="size-4"/></Link></Button></article>:<article className="rounded-[24px] border border-rule bg-white p-5 shadow-card"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-pencil/8 text-pencil"><ShieldCheck className="size-5"/></span><div className="min-w-0 flex-1"><h2 className="text-xl font-bold leading-tight tracking-[-.025em]">{openCase?.title??"Exact duplicate check is current"}</h2><p className="mt-1 text-sm leading-5 text-muted">{openCase?"Budgefi saved both transaction records so you can compare them before deciding.":"Budgefi checks current connected and manual transaction records for exact duplicate charges."}</p></div></div><Button asChild className="mt-4 w-full" variant={openCase?"default":"outline"}><Link to={openCase?`/review/${openCase.id}`:"/review"}>{openCase?"Review both charges":"View exception queue"}</Link></Button></article>}
    </section>
    <section className="mt-8" aria-labelledby="coming-up-heading"><div className="mb-3 flex items-center justify-between"><div><p className="eyebrow">Next {authoritativeProjection.planningHorizonDays} days</p><h2 id="coming-up-heading" className="text-xl font-bold tracking-[-.025em]">Coming up</h2></div><Button asChild size="sm" variant="ghost"><Link to="/plan">See plan</Link></Button></div><div className="divide-y divide-ink/8 overflow-hidden rounded-[22px] border border-ink/10 bg-white">{upcoming.map(({icon:Icon,label,meta,amount})=><Link key={label} to="/plan" className="flex min-h-[72px] items-center gap-3 px-4 py-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-cobalt"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-paper-deep text-cobalt"><Icon className="size-5"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{label}</span><span className="block truncate text-xs text-muted">{meta}</span></span><span className="text-sm font-bold tabular-nums">{amount}</span><ChevronRight className="size-4 text-muted"/></Link>)}{upcoming.length===0&&<div className="p-5 text-center"><strong className="block text-sm">Nothing dated in this horizon</strong><p className="mt-1 text-xs leading-5 text-muted">Add the next bill or obligation you want Budgefi to reserve.</p><Button asChild variant="outline" className="mt-3"><Link to="/manual">Add commitment</Link></Button></div>}</div></section>
  </main></MobileShell>;
}
function formatDate(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`))}
