import { Link, NavLink, useLocation, useNavigate } from 'react-router-dom'
import { ChevronLeft, ChevronRight, RefreshCw, Users } from 'lucide-react'
import { ActivityIcon, MoreIcon, PlanIcon, ReviewIcon, TodayIcon, MissingSourceIcon, ObservedIcon } from '@/components/icons'
import { Wordmark } from '@/components/brand'
import { Sheet, SheetClose, SheetContent, SheetTrigger } from '@/components/ui/sheet'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { useAppState } from '@/state/app-state'
import { cn } from '@/lib/utils'
import { useState } from 'react'

const nav=[['/today','Today',TodayIcon],['/review','Review',ReviewIcon],['/plan','Plan',PlanIcon],['/activity','Activity',ActivityIcon],['/more','More',MoreIcon]] as const
export function MobileShell({children}:{children:React.ReactNode}){const loc=useLocation();const detail=loc.pathname.startsWith('/review/')||loc.pathname.startsWith('/accounts/')||loc.pathname.startsWith('/connections')||loc.pathname.startsWith('/settings');return <div className="min-h-dvh bg-[#ded8ca] sm:px-4 sm:py-4"><div className="paper-grain relative mx-auto min-h-dvh w-full max-w-[430px] overflow-x-hidden sm:min-h-[calc(100dvh-32px)] sm:rounded-[26px] sm:border sm:border-carbon/10 sm:shadow-2xl"><TopBar detail={detail}/><div className={cn(detail?'pb-6':'safe-bottom')}>{children}</div>{!detail&&<BottomNav/>}</div></div>}

function TopBar({detail}:{detail:boolean}){const navg=useNavigate();const {sourceStale}=useAppState();return <header className="sticky top-0 z-30 flex h-16 items-center gap-2 border-b border-rule/80 bg-paper/95 px-4 backdrop-blur-sm">{detail?<button onClick={()=>navg(-1)} className="grid size-11 shrink-0 place-items-center rounded-xl border border-transparent hover:bg-recessed focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil" aria-label="Back"><ChevronLeft className="size-6"/></button>:<Wordmark compact/>}<span className="ml-auto rounded-full bg-pencil/8 px-2 py-1 text-[9px] font-bold uppercase tracking-[.1em] text-pencil">Sample</span><div className="flex shrink-0 items-center gap-2"><Sheet><SheetTrigger asChild><button className="grid size-11 shrink-0 place-items-center rounded-xl border border-rule bg-sheet hover:bg-recessed focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil" aria-label="Open Maya and Alex household"><Users className="size-[19px]" strokeWidth={1.8}/></button></SheetTrigger><SheetContent title="Maya & Alex" description="Shared household"><div className="rounded-xl border border-rule"><div className="flex min-h-14 w-full items-center justify-between px-3"><span><b>Maya</b><small className="block text-carbon/55">You · full access</small></span><Badge tone="blue">Active</Badge></div><div className="border-t border-rule"/><div className="flex min-h-14 w-full items-center justify-between px-3"><span><b>Alex</b><small className="block text-carbon/55">Household member</small></span><Badge>Member</Badge></div></div><SheetClose asChild><Button asChild variant="secondary" className="mt-4 w-full"><Link to="/more">Manage household</Link></Button></SheetClose></SheetContent></Sheet><HealthSheet><button className={cn('flex h-11 min-w-[82px] shrink-0 items-center justify-center gap-2 rounded-xl border px-2.5 text-[13px] font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil',sourceStale?'border-coral/35 bg-sheet text-carbon':'border-leaf/25 bg-sheet text-leaf')}><MissingSourceIcon className="size-4"/><span>{sourceStale?'1 stale':'Current'}</span></button></HealthSheet></div></header>}

export function HealthSheet({children}:{children:React.ReactNode}){const {sourceStale,setSourceStale}=useAppState();const [checking,setChecking]=useState(false);const reconnect=()=>{setChecking(true);setTimeout(()=>{setSourceStale(false);setChecking(false)},900)};return <Sheet><SheetTrigger asChild>{children}</SheetTrigger><SheetContent title="Source health" description={sourceStale?'Three sources are current. One leaves this plan based on partial data.':'All sources used by this plan are current.'}><div className="space-y-2"><SourceRow name="Chase Checking •42" note="Current through Aug 29 · 7:42 AM" impact="Included in observed cash"/><SourceRow name="Joint Cash •07" note="Current through Aug 29 · 7:38 AM" impact="Included in observed cash"/><SourceRow name="Visa •19" note="Current through Aug 28 · 11:10 PM" impact="Used for posted spending and card obligations"/><SourceRow name="MetroCard" note={sourceStale?'Stale after Aug 26':'Current through Aug 29'} impact={sourceStale?'Recent spending may be missing':'No new activity found'} stale={sourceStale}/></div>{sourceStale?<Button onClick={reconnect} disabled={checking} className="mt-5 w-full">{checking?<><RefreshCw className="size-4 animate-spin"/>Checking source…</>:'Fix MetroCard connection'}</Button>:<div className="mt-5 flex items-center gap-3 rounded-xl bg-leaf/8 p-4 text-leaf"><ObservedIcon className="size-6"/><div><b>Coverage restored</b><p className="text-sm">The plan now uses current coverage.</p></div></div>}</SheetContent></Sheet>}
function SourceRow({name,note,impact,stale=false}:{name:string;note:string;impact:string;stale?:boolean}){return <div className="flex min-h-[72px] items-center gap-3 rounded-xl border border-rule bg-sheet p-3"><span className={cn('grid size-10 shrink-0 place-items-center rounded-lg',stale?'bg-coral/8 text-coral':'bg-pencil/8 text-pencil')}>{stale?<MissingSourceIcon className="size-5"/>:<ObservedIcon className="size-5"/>}</span><div className="min-w-0"><b>{name}</b><p className="text-xs text-carbon/60">{note}</p><p className="text-xs font-medium">{impact}</p></div></div>}

function BottomNav(){const {reviewSaved,grocerySaved}=useAppState();const count=(reviewSaved?0:1)+(grocerySaved?0:1);return <nav className="fixed inset-x-0 bottom-0 z-40 mx-auto grid h-[86px] max-w-[430px] grid-cols-5 border-t border-rule bg-sheet/97 pb-[env(safe-area-inset-bottom)] backdrop-blur-sm sm:bottom-4 sm:rounded-b-[26px]" aria-label="Primary navigation">{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/today'} className={({isActive})=>cn('relative flex min-w-0 flex-col items-center justify-center gap-1.5 text-[11.5px] font-semibold text-carbon/65 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-pencil',isActive&&'text-pencil')} children={({isActive})=><><span className={cn('relative grid size-11 place-items-center rounded-xl transition-colors',isActive&&'bg-citron')}><Icon className="size-6" strokeWidth={1.9}/>{label==='Review'&&count>0&&<span className="tabular absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-pencil text-[10px] font-bold text-white">{count}</span>}</span><span>{label}</span></>}/>)}</nav>}
