import { ChevronRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet'
import { calculatePlanProjection, useAppState } from '@/state/app-state'
import { cn, money } from '@/lib/utils'

export function MoneySummary({variant='full'}:{variant?:'full'|'compact'}) { const {sourceStale,calibration,planningBuffer}=useAppState(); const {available,reserved}=calculatePlanProjection(calibration,planningBuffer); const shortfall=available<0; return <section className="relative overflow-hidden rounded-[22px] border border-rule bg-sheet p-5 shadow-sheet">
  <div className="flex items-center justify-between gap-3"><p className="text-[11px] font-bold uppercase tracking-[.13em] text-carbon/55">{shortfall?'Projected shortfall':sourceStale?'Plan preview':'Available to use'}</p>{sourceStale&&<span className="rounded-full bg-recessed px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em]">Partial data</span>}</div>
  <div className="mt-2"><p className={cn('tabular font-sans font-bold leading-none tracking-[-.055em]',shortfall&&'text-coral',variant==='compact'?'text-[39px]':'text-[44px]')}>{money(Math.abs(available))}</p><p className="mt-2 font-display text-[19px] italic leading-none text-carbon/75">{shortfall?'by September 8':sourceStale?'Before unobserved activity · through September 8':'through September 8'}</p></div>
  {shortfall&&variant==='full'&&<Button asChild variant="outline" className="mt-4 w-full"><Link to="/settings/calibration">Adjust the plan</Link></Button>}
  {variant==='full'&&<Sheet><SheetTrigger asChild><button className="mt-5 grid min-h-[66px] w-full grid-cols-[1fr_1fr_auto] items-center gap-3 border-t border-rule pt-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil"><span><span className="block text-[10px] font-bold uppercase tracking-[.1em] text-carbon/50">Known cash</span><strong className="tabular mt-0.5 block text-sm">{money(calibration.knownCash)}</strong></span><span className="border-l border-rule pl-3"><span className="block text-[10px] font-bold uppercase tracking-[.1em] text-carbon/50">Reserved</span><strong className="tabular mt-0.5 block text-sm">{money(reserved)}</strong></span><ChevronRight className="size-4 text-pencil"/></button></SheetTrigger><SheetContent title="How this is calculated" description="Planning period · Aug 23–Sep 8"><Calculation available={available}/></SheetContent></Sheet>}
</section> }

export function Calculation({available}:{available:number}) { const {calibration,planningBuffer,sourceStale}=useAppState(); const {futureBills}=calculatePlanProjection(calibration,planningBuffer); const includedCount=Number(calibration.includeChase)+Number(calibration.includeJoint); const commitmentCount=4+calibration.customCommitments.length; const rows=[[calibration.cashProvenance==='user_entered'?'You-entered cash':'Observed cash',calibration.knownCash,`${includedCount} included deposit ${includedCount===1?'account':'accounts'} · Aug 29`],['Reviewed commitments',-futureBills,`${commitmentCount} uncleared items through Sep 8`],['Planned savings',-calibration.savingsContribution,'Reserved now for this planning horizon'],['Safety buffer',-planningBuffer,'You entered']]; const shortfall=available<0; return <div><div className="divide-y divide-rule rounded-xl border border-rule">{rows.map(([label,value,note])=><div className="flex items-center justify-between gap-4 p-3" key={label as string}><div><div className="font-medium">{label}</div><div className="text-xs text-carbon/55">{note}</div></div><div className="tabular font-semibold">{Number(value)>0?'':'−'}{money(Math.abs(Number(value)))}</div></div>)}<div className="flex items-center justify-between bg-recessed/65 p-3 text-lg font-bold"><span>{shortfall?'Projected shortfall':sourceStale?'Partial-data preview':'Available to use'}</span><span className={cn('tabular',shortfall&&'text-coral')}>{money(Math.abs(available))}</span></div></div><p className="mt-4 text-sm text-carbon/65">No future income is counted until it is received. The cleared MetroNet charge is already reflected in cash and is not subtracted again.</p></div> }
