import { useState } from "react";
import { ChevronRight, Landmark, Plus, Trash2, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { calculatePlanProjection, type IncomeFrequency, type PlanCalibrationData, useAppState } from "@/state/app-state";
import { cn, money } from "@/lib/utils";

const stageNames = ["Cash scope", "Income timing", "Commitments", "Guardrails"];
let commitmentSequence=0;
const createCommitmentId=()=>`custom-${Date.now().toString(36)}-${(commitmentSequence++).toString(36)}`;

export function PlanCalibration({ onComplete, onBack, onDraftComplete, embedded = false }: { onComplete?: () => void; onBack?: () => void; onDraftComplete?: (data:PlanCalibrationData,buffer:number)=>void; embedded?: boolean }) {
  const state = useAppState();
  const [stage, setStage] = useState(0);
  const [draft, setDraft] = useState<PlanCalibrationData>(state.calibration);
  const [buffer, setBuffer] = useState(state.planningBuffer);
  const [includeChase, setIncludeChase] = useState(state.calibration.includeChase);
  const [includeJoint, setIncludeJoint] = useState(state.calibration.includeJoint);
  const [cashEdited, setCashEdited] = useState(state.calibration.cashProvenance === 'user_entered');
  const projection = calculatePlanProjection(draft, buffer);
  const customInvalid=draft.customCommitments.some(item=>!item.name.trim()||item.amount<=0);

  const setIncluded = (chase: boolean, joint: boolean) => {
    setIncludeChase(chase); setIncludeJoint(joint);
    setCashEdited(false);
    setDraft(value => ({ ...value, includeChase: chase, includeJoint: joint, cashProvenance: 'observed', knownCash: (chase ? 3940.39 : 0) + (joint ? 290 : 0) }));
  };
  const finish = () => { const completed={ ...draft, includeChase, includeJoint, cashProvenance: cashEdited ? 'user_entered' as const : 'observed' as const, electricMax: Math.max(130, draft.electricMax) }; if(onDraftComplete)onDraftComplete(completed,buffer);else state.savePlanCalibration(completed,buffer); onComplete?.(); };

  return <div className={cn("flex flex-1 flex-col", !embedded && "min-h-[calc(100dvh-126px)]")}>
    <div className="mb-5"><div className="grid grid-cols-4 gap-1.5" aria-label={`Plan setup step ${stage + 1} of 4`}>{stageNames.map((name,index)=><span key={name} className={cn("h-1 rounded-full",index<=stage?"bg-pencil":"bg-carbon/12")}/>)}</div><p className="mt-2 text-right text-[10px] font-bold uppercase tracking-[.1em] text-muted">Plan setup · {stage+1} of 4</p></div>
    {stage===0&&<CashScope draft={draft} setDraft={setDraft} includeChase={includeChase} includeJoint={includeJoint} setIncluded={setIncluded} cashEdited={cashEdited} setCashEdited={setCashEdited}/>} 
    {stage===1&&<IncomeTiming draft={draft} setDraft={setDraft}/>} 
    {stage===2&&<Commitments draft={draft} setDraft={setDraft}/>} 
    {stage===3&&<Guardrails draft={draft} setDraft={setDraft} buffer={buffer} setBuffer={setBuffer} projection={projection} stale={state.sourceStale}/>} 
    <div className="mt-auto grid grid-cols-[auto_1fr] gap-2 pt-6"><Button variant="outline" size="lg" onClick={()=>stage===0?onBack?.():setStage(value=>value-1)}>Back</Button><Button size="lg" disabled={(stage===0&&draft.knownCash<=0)||(stage===2&&customInvalid)||(stage===3&&projection.available<0)} onClick={()=>stage<3?setStage(value=>value+1):finish()}>{stage<3?<>Continue <ChevronRight className="size-4"/></>:"Use this plan"}</Button></div>
    {stage===0&&draft.knownCash<=0&&<p className="mt-2 text-center text-xs text-coral">Include at least one spendable cash account.</p>}
    {stage===2&&customInvalid&&<p className="mt-2 text-center text-xs text-coral">Name each added commitment and enter an amount above $0, or remove it.</p>}
  </div>;
}

function CashScope({draft,setDraft,includeChase,includeJoint,setIncluded,cashEdited,setCashEdited}:{draft:PlanCalibrationData;setDraft:React.Dispatch<React.SetStateAction<PlanCalibrationData>>;includeChase:boolean;includeJoint:boolean;setIncluded:(chase:boolean,joint:boolean)=>void;cashEdited:boolean;setCashEdited:(value:boolean)=>void}){
  return <section><p className="eyebrow">Observed cash</p><h1 className="text-[29px] font-bold leading-tight tracking-[-.045em]">Which cash can this plan use?</h1><p className="mt-2 text-sm leading-5 text-muted">Include deposit balances that can actually pay household commitments. Credit availability is never cash.</p><div className="mt-5 space-y-2"><AccountScope name="Chase Checking •42" detail="Observed Aug 29 · 7:42 AM" amount={3940.39} included={includeChase} onChange={value=>setIncluded(value,includeJoint)}/><AccountScope name="Joint Cash •07" detail="Observed Aug 29 · 7:38 AM" amount={290} included={includeJoint} onChange={value=>setIncluded(includeChase,value)}/><AccountScope name="Emergency Savings •16" detail="Excluded from spending by default" amount={6200} included={false} onChange={()=>{}} locked/></div><div className="mt-4 rounded-[20px] border border-pencil/15 bg-pencil/[.035] p-4"><div className="flex items-center justify-between"><span><span className="block text-[10px] font-bold uppercase tracking-[.1em] text-muted">Included cash</span><strong className="tabular mt-1 block text-2xl">{money(draft.knownCash)}</strong></span><Provenance label={cashEdited?"You entered":"Observed"}/></div><label htmlFor="cash-correction" className="mt-4 block text-xs font-semibold">Correct the included total</label><div className="mt-2 flex h-12 items-center rounded-xl border border-rule bg-white px-3 focus-within:ring-2 focus-within:ring-pencil"><span className="text-muted">$</span><input id="cash-correction" type="number" inputMode="decimal" min="0" value={draft.knownCash} onChange={event=>{setCashEdited(true);setDraft(value=>({...value,knownCash:Math.max(0,Number(event.target.value)||0)}))}} className="h-full min-w-0 flex-1 bg-transparent px-2 text-base font-bold outline-none"/></div><p className="mt-2 text-[11px] leading-4 text-muted">Manual corrections remain visibly labeled and can be reviewed later.</p></div></section>
}

function IncomeTiming({draft,setDraft}:{draft:PlanCalibrationData;setDraft:React.Dispatch<React.SetStateAction<PlanCalibrationData>>}){
  const inside=draft.nextIncomeDate>="2026-08-29"&&draft.nextIncomeDate<="2026-09-08";
  return <section><p className="eyebrow">Detected schedule</p><h1 className="text-[29px] font-bold leading-tight tracking-[-.045em]">When is money coming in?</h1><p className="mt-2 text-sm leading-5 text-muted">Confirm the schedule for forecasting. Future deposits remain excluded from available-to-use until observed.</p><div className="mt-5 rounded-[20px] border border-rule bg-white p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2"><WalletCards className="size-5 text-pencil"/><strong className="text-sm">Primary paycheck</strong></span><Provenance label="Detected"/></div><div className="mt-4 grid grid-cols-2 gap-3"><Field label="Typical net amount"><MoneyInput value={draft.incomeAmount} onChange={incomeAmount=>setDraft(value=>({...value,incomeAmount}))}/></Field><Field label="Next expected date"><input type="date" value={draft.nextIncomeDate} onChange={event=>setDraft(value=>({...value,nextIncomeDate:event.target.value}))} className="h-12 w-full rounded-xl border border-rule bg-white px-3 text-base outline-none focus:ring-2 focus:ring-pencil"/></Field></div><label className="mt-4 block text-xs font-semibold" htmlFor="income-frequency">Pay frequency</label><select id="income-frequency" value={draft.incomeFrequency} onChange={event=>setDraft(value=>({...value,incomeFrequency:event.target.value as IncomeFrequency,incomeConfirmed:event.target.value==='irregular'?false:value.incomeConfirmed}))} className="mt-2 h-12 w-full rounded-xl border border-rule bg-white px-3 text-base outline-none focus:ring-2 focus:ring-pencil"><option value="weekly">Weekly</option><option value="biweekly">Every two weeks</option><option value="semi_monthly">Twice a month</option><option value="monthly">Monthly</option><option value="irregular">Irregular</option></select><div className="mt-4 flex items-center justify-between gap-3 rounded-2xl bg-recessed p-3"><span><strong className="block text-sm">Schedule looks right</strong><span className="text-xs text-muted">Confirmation improves the timeline, not cash</span></span><Switch checked={draft.incomeConfirmed} onCheckedChange={incomeConfirmed=>setDraft(value=>({...value,incomeConfirmed}))} label="Confirm income schedule"/></div></div><div className={cn("mt-4 rounded-2xl p-4 text-sm",inside?"border border-pencil/15 bg-pencil/[.035]":"bg-recessed")}><strong>{inside?`${money(draft.incomeAmount)} expected before Sep 8`:`Next pay is after Sep 8`}</strong><p className="mt-1 text-xs leading-5 text-muted">Not counted until received. Reimbursements and transfers are also excluded.</p></div></section>
}

function Commitments({draft,setDraft}:{draft:PlanCalibrationData;setDraft:React.Dispatch<React.SetStateAction<PlanCalibrationData>>}){
  const items:["rentAmount"|"electricMax"|"streamBoxAmount"|"insuranceAmount",string,string,string][]=[["rentAmount","Rent","Sep 1","Confirmed"],["electricMax","Electric maximum","Sep 4","Estimated"],["streamBoxAmount","StreamBox","Sep 6","Detected"],["insuranceAmount","Auto insurance","Sep 8","Detected"]];
  const update=(key:"rentAmount"|"electricMax"|"streamBoxAmount"|"insuranceAmount",raw:number)=>setDraft(value=>({...value,[key]:key==='electricMax'?Math.max(130,raw):Math.max(0,raw),editedCommitments:value.editedCommitments.includes(key)?value.editedCommitments:[...value.editedCommitments,key]}));
  const add=()=>setDraft(value=>({...value,customCommitments:[...value.customCommitments,{id:createCommitmentId(),name:"",amount:0}]}));
  const updateCustom=(id:string,patch:Partial<{name:string;amount:number}>)=>setDraft(value=>({...value,customCommitments:value.customCommitments.map(item=>item.id===id?{...item,...patch}:item)}));
  const removeCustom=(id:string)=>setDraft(value=>({...value,customCommitments:value.customCommitments.filter(item=>item.id!==id)}));
  const total=draft.rentAmount+Math.max(130,draft.electricMax)+draft.streamBoxAmount+draft.insuranceAmount+draft.customCommitments.reduce((sum,item)=>sum+item.amount,0);
  return <section>
    <p className="eyebrow">Through September 8</p><h1 className="text-[29px] font-bold leading-tight tracking-[-.045em]">What must be paid?</h1><p className="mt-2 text-sm leading-5 text-muted">Review the detected commitments. Cleared charges and transfers between included accounts are excluded.</p>
    <div className="mt-5 overflow-hidden rounded-[20px] border border-rule bg-white">{items.map(([key,name,date,source])=><div key={key} className="grid min-h-[72px] grid-cols-[1fr_104px] items-center gap-3 border-b border-rule px-4 py-3 last:border-0"><span><strong className="block text-sm">{name}</strong><span className="text-xs text-muted">{date} · {draft.editedCommitments.includes(key)?'You entered':source}</span></span><div className="flex h-11 items-center rounded-xl border border-rule px-2 focus-within:ring-2 focus-within:ring-pencil"><span className="text-sm text-muted">$</span><input aria-label={`${name} amount`} type="number" min={key==='electricMax'?130:0} step="0.01" value={draft[key]} onChange={event=>update(key,Number(event.target.value)||0)} className="h-full min-w-0 flex-1 bg-transparent px-1 text-right text-base font-bold outline-none"/></div></div>)}</div>
    {draft.customCommitments.map(item=><div key={item.id} className="mt-2 grid grid-cols-[1fr_96px_44px] items-center gap-2 rounded-2xl border border-pencil/15 bg-white p-2"><input aria-label="Custom commitment name" value={item.name} onChange={event=>updateCustom(item.id,{name:event.target.value})} className="h-11 min-w-0 rounded-xl border border-rule px-3 text-sm font-semibold outline-none focus:ring-2 focus:ring-pencil"/><div className="flex h-11 items-center rounded-xl border border-rule px-2"><span className="text-sm text-muted">$</span><input aria-label={`${item.name} amount`} type="number" min="0" step="0.01" value={item.amount} onChange={event=>updateCustom(item.id,{amount:Math.max(0,Number(event.target.value)||0)})} className="min-w-0 flex-1 bg-transparent px-1 text-right text-sm font-bold outline-none"/></div><button onClick={()=>removeCustom(item.id)} className="grid size-11 place-items-center rounded-xl text-coral focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pencil" aria-label={`Remove ${item.name}`}><Trash2 className="size-4"/></button></div>)}
    <Button type="button" variant="outline" onClick={add} className="mt-3 w-full"><Plus className="size-4"/>Add missing commitment</Button>
    <div className="mt-4 flex items-center justify-between rounded-2xl bg-recessed p-4"><span><span className="block text-[10px] font-bold uppercase tracking-[.1em] text-muted">Reserved for commitments</span><strong className="tabular mt-1 block text-xl">{money(total)}</strong></span><Provenance label="Reviewed"/></div><p className="mt-3 text-xs leading-5 text-muted">MetroNet’s cleared $83.20 is already reflected in cash and is not subtracted again.</p>
  </section>
}

function Guardrails({draft,setDraft,buffer,setBuffer,projection,stale}:{draft:PlanCalibrationData;setDraft:React.Dispatch<React.SetStateAction<PlanCalibrationData>>;buffer:number;setBuffer:(value:number)=>void;projection:ReturnType<typeof calculatePlanProjection>;stale:boolean}){
  const shortfall=projection.available<0;
  return <section><p className="eyebrow">Guardrails and preview</p><h1 className="text-[29px] font-bold leading-tight tracking-[-.045em]">What should stay protected?</h1><p className="mt-2 text-sm leading-5 text-muted">Savings is reserved now for this horizon, not shown as a completed transfer. The buffer remains untouched for surprises.</p><div className="mt-5 grid grid-cols-1 gap-3 min-[370px]:grid-cols-2"><Field label="Planned savings"><MoneyInput value={draft.savingsContribution} onChange={savingsContribution=>setDraft(value=>({...value,savingsContribution}))}/></Field><Field label="Safety buffer"><MoneyInput value={buffer} onChange={setBuffer}/></Field></div><div className="mt-5 overflow-hidden rounded-[22px] bg-ink p-4 text-white"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-citron">{shortfall?"Projected shortfall":stale?"Partial-data preview":"Available to use"}</p>{stale&&<span className="rounded-full bg-white/10 px-2 py-1 text-[9px] font-bold uppercase tracking-[.08em]">Coverage incomplete</span>}</div><p className="tabular mt-2 text-[36px] font-bold tracking-[-.05em]">{money(Math.abs(projection.available))}</p><div className="mt-4 space-y-2 border-t border-white/15 pt-3 text-xs text-white/70"><Equation label={draft.cashProvenance==='user_entered'?"You-entered cash":"Observed cash"} value={draft.knownCash}/><Equation label="Reviewed commitments" value={-projection.futureBills}/><Equation label="Planned savings" value={-draft.savingsContribution}/><Equation label="Safety buffer" value={-buffer}/></div><p className="mt-4 text-[11px] leading-5 text-white/55">No future income counted. Lowest projected balance occurs Sep 8.</p></div>{stale&&<div className="mt-3 rounded-2xl border border-coral/20 bg-coral/[.05] p-3 text-xs leading-5 text-muted">MetroCard coverage is incomplete. Treat this as a preview until the source refreshes.</div>}{shortfall&&<div className="mt-3 rounded-2xl border border-coral/20 bg-coral/[.05] p-3 text-xs leading-5 text-muted">The plan does not cover all reviewed commitments and guardrails. Go back to adjust the inputs before relying on it.</div>}</section>
}

function AccountScope({name,detail,amount,included,onChange,locked=false}:{name:string;detail:string;amount:number;included:boolean;onChange:(value:boolean)=>void;locked?:boolean}){return <div className="flex min-h-[70px] items-center gap-3 rounded-2xl border border-rule bg-white p-3"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-recessed text-pencil"><Landmark className="size-5"/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{name}</strong><span className="block text-xs text-muted">{detail}</span></span><span className="text-right"><strong className="tabular block text-sm">{money(amount)}</strong>{locked?<span className="text-[10px] font-bold uppercase text-muted">Protected</span>:<Switch checked={included} onCheckedChange={onChange} label={`Include ${name}`}/>}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-semibold"><span className="mb-2 block">{label}</span>{children}</label>}
function MoneyInput({value,onChange}:{value:number;onChange:(value:number)=>void}){return <div className="flex h-12 items-center rounded-xl border border-rule bg-white px-3 focus-within:ring-2 focus-within:ring-pencil"><span className="text-muted">$</span><input type="number" inputMode="decimal" min="0" step="0.01" value={value} onChange={event=>onChange(Math.max(0,Number(event.target.value)||0))} className="h-full min-w-0 flex-1 bg-transparent px-1 text-base font-bold outline-none"/></div>}
function Provenance({label}:{label:string}){return <span className="rounded-full border border-pencil/15 bg-white px-2 py-1 text-[9px] font-bold uppercase tracking-[.08em] text-pencil">{label}</span>}
function Equation({label,value}:{label:string;value:number}){return <div className="flex justify-between gap-3"><span>{label}</span><strong className="tabular text-white">{value<0?'−':''}{money(Math.abs(value))}</strong></div>}
