import { createContext, useContext, useMemo, useState } from 'react'
export type ReviewAnswer='expected'|'unexpected'|'unsure'|null
export type PlanChoice='watch'|'update'|'contact'|null
export type GroceryAnswer='both'|'duplicate'|'unsure'|null
export type HouseholdMode='solo'|'shared'
export type NotificationMode='exceptions'|'daily'|'all'
export type IncomeFrequency='weekly'|'biweekly'|'semi_monthly'|'monthly'|'irregular'
export type CustomCommitment={id:string;name:string;amount:number}
export type PlanCalibrationData={knownCash:number;includeChase:boolean;includeJoint:boolean;cashProvenance:'observed'|'user_entered';incomeAmount:number;incomeFrequency:IncomeFrequency;nextIncomeDate:string;incomeConfirmed:boolean;rentAmount:number;electricMax:number;streamBoxAmount:number;insuranceAmount:number;editedCommitments:string[];customCommitments:CustomCommitment[];savingsContribution:number}
export const defaultCalibration:PlanCalibrationData={knownCash:4230.39,includeChase:true,includeJoint:true,cashProvenance:'observed',incomeAmount:2200,incomeFrequency:'biweekly',nextIncomeDate:'2026-09-11',incomeConfirmed:true,rentAmount:1850,electricMax:155,streamBoxAmount:18.99,insuranceAmount:142.40,editedCommitments:[],customCommitments:[],savingsContribution:500}
export function calculatePlanProjection(calibration:PlanCalibrationData,planningBuffer:number){const cents=(value:number)=>Math.round(value*100);const incomeInWindow=0;const customCents=calibration.customCommitments.reduce((sum,item)=>sum+cents(item.amount),0);const futureBillsCents=cents(calibration.rentAmount)+cents(Math.max(130,calibration.electricMax))+cents(calibration.streamBoxAmount)+cents(calibration.insuranceAmount)+customCents;const reservedCents=futureBillsCents+cents(calibration.savingsContribution)+cents(planningBuffer);return {incomeInWindow,futureBills:futureBillsCents/100,reserved:reservedCents/100,available:(cents(calibration.knownCash)-reservedCents)/100}}
export type EventItem={id:string;title:string;detail:string;time:string;type:'evidence'|'plan'|'source'|'household'}
export type ActivityEvent=EventItem
type State={sourceStale:boolean;reviewAnswer:ReviewAnswer;planChoice:PlanChoice;reviewSaved:boolean;groceryAnswer:GroceryAnswer;grocerySaved:boolean;calibration:PlanCalibrationData;planCalibrated:boolean;electricMax:number;planningBuffer:number;householdMode:HouseholdMode;notificationMode:NotificationMode;weeklyDigest:boolean;demoBankConnected:boolean;onboardingCompleted:boolean;events:EventItem[];setSourceStale:(v:boolean)=>void;setReviewAnswer:(v:ReviewAnswer)=>void;setPlanChoice:(v:PlanChoice)=>void;setGroceryAnswer:(v:GroceryAnswer)=>void;setHouseholdMode:(v:HouseholdMode)=>void;setNotificationMode:(v:NotificationMode)=>void;setWeeklyDigest:(v:boolean)=>void;setOnboardingCompleted:(v:boolean)=>void;connectDemoBank:()=>void;disconnectDemoBank:()=>void;saveReview:()=>void;saveGrocery:()=>void;saveElectric:(v:number)=>void;savePlanningBuffer:(v:number)=>void;savePlanCalibration:(v:PlanCalibrationData,buffer:number)=>void;reset:()=>void}
const initialEvents:EventItem[]=[
 {id:'e1',title:'MetroNet difference detected',detail:'Expected $65.00 · observed $83.20',time:'Today · 8:04 AM',type:'evidence'},
 {id:'e2',title:'Chase statement checked',detail:'Coverage Aug 1–29 · fetched at 7:42 AM',time:'Today · 7:42 AM',type:'source'},
 {id:'e3',title:'Rent amount confirmed by Alex',detail:'Amount confirmed · payment not observed',time:'Yesterday · 6:18 PM',type:'household'},
]
const C=createContext<State|null>(null)
export function AppStateProvider({children}:{children:React.ReactNode}){const [sourceStale,setSourceStaleRaw]=useState(true);const [reviewAnswer,setReviewAnswer]=useState<ReviewAnswer>(null);const [planChoice,setPlanChoice]=useState<PlanChoice>(null);const [reviewSaved,setReviewSaved]=useState(false);const [groceryAnswer,setGroceryAnswer]=useState<GroceryAnswer>(null);const [grocerySaved,setGrocerySaved]=useState(false);const [calibration,setCalibration]=useState<PlanCalibrationData>(defaultCalibration);const [planCalibrated,setPlanCalibrated]=useState(true);const electricMax=calibration.electricMax;const [planningBuffer,setPlanningBuffer]=useState(280);const [householdMode,setHouseholdMode]=useState<HouseholdMode>('shared');const [notificationMode,setNotificationMode]=useState<NotificationMode>('exceptions');const [weeklyDigest,setWeeklyDigest]=useState(true);const [demoBankConnected,setDemoBankConnected]=useState(false);const [onboardingCompleted,setOnboardingCompleted]=useState(true);const [events,setEvents]=useState(initialEvents)
 const add=(e:EventItem)=>setEvents(x=>[e,...x.filter(i=>i.id!==e.id)])
 const setSourceStale=(v:boolean)=>{setSourceStaleRaw(v);if(!v)add({id:'source-fixed',title:'MetroCard source restored',detail:'Coverage checked through Aug 29 · no new activity',time:'Just now',type:'source'})}
 const saveReview=()=>{setReviewSaved(true);add({id:'review-saved',title:'MetroNet plan saved',detail:planChoice==='update'?'Next expected bill updated to $83.20':'Evidence saved · next charge will be watched',time:'Just now',type:'evidence'})}
 const saveGrocery=()=>{setGrocerySaved(true);add({id:'grocery-saved',title:'Green Basket review completed',detail:groceryAnswer==='both'?'Both charges confirmed':'Possible duplicate recorded · statement will be watched',time:'Just now',type:'evidence'})}
 const saveElectric=(v:number)=>{const maximum=Math.max(130,v);setCalibration(value=>({...value,electricMax:maximum,editedCommitments:value.editedCommitments.includes('electricMax')?value.editedCommitments:[...value.editedCommitments,'electricMax']}));add({id:'electric-saved',title:'Electric reserve updated',detail:`Maximum changed to $${maximum} · projection recalculated`,time:'Just now',type:'plan'})}
 const savePlanningBuffer=(v:number)=>{setPlanningBuffer(v);add({id:'buffer-saved',title:'Safety buffer updated',detail:`Household buffer changed to $${v}`,time:'Just now',type:'plan'})}
 const savePlanCalibration=(v:PlanCalibrationData,buffer:number)=>{setCalibration(v);setPlanningBuffer(buffer);setPlanCalibrated(true);const projection=calculatePlanProjection(v,buffer);add({id:'plan-calibrated',title:'Plan inputs confirmed',detail:`${v.incomeConfirmed?'Income schedule confirmed':'Income excluded'} · $${projection.futureBills.toFixed(2)} commitments reserved`,time:'Just now',type:'plan'})}
 const connectDemoBank=()=>{setDemoBankConnected(true);add({id:'demo-bank-connected',title:'Sample source connected',detail:'Chase Checking •42 and Joint Cash •07 · read-only',time:'Just now',type:'source'})}
 const disconnectDemoBank=()=>{setDemoBankConnected(false);add({id:'demo-bank-disconnected',title:'Sample source disconnected',detail:'Demo access removed · historical evidence retained',time:'Just now',type:'source'})}
 const reset=()=>{setSourceStaleRaw(true);setReviewAnswer(null);setPlanChoice(null);setReviewSaved(false);setGroceryAnswer(null);setGrocerySaved(false);setCalibration(defaultCalibration);setPlanCalibrated(true);setPlanningBuffer(280);setHouseholdMode('shared');setNotificationMode('exceptions');setWeeklyDigest(true);setDemoBankConnected(false);setOnboardingCompleted(true);setEvents(initialEvents)}
 const value=useMemo(()=>({sourceStale,reviewAnswer,planChoice,reviewSaved,groceryAnswer,grocerySaved,calibration,planCalibrated,electricMax,planningBuffer,householdMode,notificationMode,weeklyDigest,demoBankConnected,onboardingCompleted,events,setSourceStale,setReviewAnswer,setPlanChoice,setGroceryAnswer,setHouseholdMode,setNotificationMode,setWeeklyDigest,setOnboardingCompleted,connectDemoBank,disconnectDemoBank,saveReview,saveGrocery,saveElectric,savePlanningBuffer,savePlanCalibration,reset}),[sourceStale,reviewAnswer,planChoice,reviewSaved,groceryAnswer,grocerySaved,calibration,planCalibrated,electricMax,planningBuffer,householdMode,notificationMode,weeklyDigest,demoBankConnected,onboardingCompleted,events])
 return <C.Provider value={value}>{children}</C.Provider>}
export function useAppState(){const v=useContext(C);if(!v)throw new Error('missing AppStateProvider');return v}
